# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SerescoMapsUtils' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SerescoMapsUtils
    pod 'Google-Maps-iOS-Utils', '3.10.3'
    pod 'CodableGeoJSON'
    pod 'Kingfisher', '~> 7.0'
end
